version: '3.8'

services:
  flask-sns-app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ../instance:/app/instance
      - ../uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: flask-sns-app 